name: deployment_exc
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
      steps:
        -name: get code
         uses: actions/checkoiut@v3
          with:
        -name: install dependicies
         run: npm ci
        -name: lint
         run: npm run lint 
  test:
    runs-on: ubuntu-latest
      steps:
        -name: get code
         uses: actions/checkoiut@v3
          with:
        -name: install dependicies
         run: npm ci
        -name: run test
         run: npm run test

  deploy:
    runs-on: ubuntu-latest
      steps:
        -name: get code
         uses: actions/checkoiut@v3
          with:
        -name: install dependicies
         run: npm ci
        -name: lint
         run: npm run lint
        -name: run test
         run: npm run test
        -name: run build
         run: npm run code
        -name: run deploy
         run: echo "deploying...."
  